fetch時にキャッシュから取得
ririringer/drawing-board pull request #3
Opened 2024-01-20 07:16 UTC by cbryotaro

# fetch時にキャッシュから取得

## やったこと
- サービスワーカーがfetch処理をキャッシュし、２回目以降はキャッシュから返却するようにしました
<img width="1268" alt="image" src="https://github.com/ririringer/drawing-board/assets/37492334/4326dd5c-030a-4cb2-b389-c62437432337">

## やってないこと
- 解せないですが `addEventListener("fetch"` が、POSTリクエスト時にも発火しているように見えます。fetchなのでPOSTリクエストはインタラプトしない認識なんですが、デバックしていると確かに発生していました。原因掴めず、GET以外は無視するようなバリデーションを入れています。
 
## 動作確認

- 開発者ツールのネットワークタブを開いた状態で `http://localhost:5173/` を表示
- 初回は以下のようにNW経由で画像を取得している
- 2回目以降は以下のようにSW経由で画像を取得している

2024-01-20 09:17 UTC, ririringer commented on public/firebase-messaging-sw.js
> +          return caches.delete(key);
キャッシュ作成ありがとうございます！！！
すいません、通知作成のための変更でもcacheを利用しているため、ここだけ`if (key !== CACHE_NAME && key.startsWith(NAME))`みたいな形にしていただけますと助かります🙇

2024-01-20 09:18 UTC, ririringer commented
全然関係ないですが、PRが見やすすぎてビビりました、、、！
参考にさせていただきます！

2024-01-20 09:20 UTC, ririringer commented on public/firebase-messaging-sw.js
> +          return caches.delete(key);
利用部分（このリポジトリをフォークしたタイミングでは入ってなかった変更です）
https://github.com/ririringer/drawing-board/blob/8827a27aa2bd59295c70a88d6bcdee1faf5793f4/public/firebase-messaging-sw.js#L46-L82

2024-01-20 09:21 UTC, ririringer commented on public/firebase-messaging-sw.js
> +          return caches.delete(key);
ブランチを直接作れた方が諸々都合がいいと思いますので、先ほどcollaboratorに招待させていただきましたmm

2024-01-21 05:03 UTC, littlebobdog requested changes

2024-01-21 11:06 UTC, cbryotaro commented on public/firebase-messaging-sw.js
>  self.addEventListener("fetch", (event) => {
なるほど！修正しました！

2024-01-21 11:07 UTC, littlebobdog approved these changes

2024-01-21 11:07 UTC, cbryotaro commented on public/firebase-messaging-sw.js
> +          return caches.delete(key);
なるほど！定数名ごと区別するようにしました 👍

2024-01-21 11:08 UTC, littlebobdog commented on public/firebase-messaging-sw.js
>  self.addEventListener("fetch", (event) => {
LGTM Resolveにします

2024-01-21 14:28 UTC, merged

2024-01-21 14:29 UTC, ririringer commented
ありがとうございます！！！マージしました！！！